<?php

return [
    \App\Api\User\BackgroundPhotoInterface::class => \App\Model\User\BackgroundPhoto::class,
    \App\Api\Image\ImageOptimizerInterface::class => \App\Model\Image\ImageOptimizer::class,
    \App\Api\User\AvatarInterface::class => \App\Model\User\Avatar::class,
    \App\Api\Uploader\FileUploaderInterface::class => \App\Model\Uploader\FileUploader::class,
    \App\Api\Authorization\AuthorizeInterface::class => \App\Model\Authorization\Authorize::class,
    \App\Api\Authtoken\TokenGeneratorInterface::class => \App\Model\Authtoken\TokenGenerator::class,
    \App\Api\Authtoken\AuthtokenInterface::class => \App\Model\Authtoken\Authtoken::class,
    \App\Api\User\UserInterface::class => \App\Model\User::class,
    \App\Api\Geo\CityInterface::class => \App\Model\Geo\City::class,
    \App\Api\Geo\RegionInterface::class => \App\Model\Geo\Region::class,
    \App\Api\Geo\CountryInterface::class => \App\Model\Geo\Country::class,
    \Core\Api\Messages\MessageManagerInterface::class => \Core\Messages\MessageManager::class,
    \Core\Api\Cookie\CookieInterface::class => \Core\Cookie\Cookie::class,
    \Core\Api\Session\SessionInterface::class => \Core\Session\Session::class,
    \Core\Api\Url\RedirectInterface::class => \Core\Url\Redirect::class,
    \Core\Api\Psr\Log\LoggerInterface::class => \Core\Psr\Log\Logger::class,
    \Core\Api\Validation\ValidatorInterface::class => \Core\Validation\Validator::class,
    \Core\Api\View\ViewServiceProviderInterface::class => \App\Provider\View\ViewServiceProvider::class,
    \Core\Api\View\ViewInterface::class => \Core\View\View::class,
    \Core\Api\Controllers\ControllerInterface::class => \Core\Controllers\Controller::class,
    \Core\Api\ActiveRecord\BuilderInterface::class => \Core\ActiveRecord\Builder::class,
    \Core\Api\Database\QueryBuilder\MySqlQueryBuilderInterface::class => \Core\Database\QueryBuilder\MySqlQueryBuilder::class,
    \Core\Api\Database\Connection\MySqlConnectionInterface::class => \Core\Database\Connection\MySqlConnection::class,
    \Core\Api\Config\DevelopmentConfigInterface::class => \Core\Config\DevelopmentConfig::class,
    \Core\Api\Router\RouteListInterface::class => \Core\Router\RouteList::class,
    \Core\Api\Di\DefinitionsInterface::class => \Core\Di\Definitions::class,
    \Core\Api\Url\UrlInterface::class => \Core\Url\Url::class,
    \Core\Api\Di\NotFoundExceptionInterface::class => \Core\Di\NotFoundException::class,
    \Core\Api\Router\DispatcherInterface::class => \Core\Router\Dispatcher::class,
    \Core\Api\Router\RouteInterface::class => \Core\Router\Route::class,
    \Core\Api\Router\RouteFactoryInterface::class => \Core\Router\RouteFactory::class,
    \Core\Api\Router\RouterInterface::class => \Core\Router\Router::class,
    \Core\Api\BootstrapInterface::class => \Core\Bootstrap::class,
    \Core\Api\Di\ContainerInterface::class => \Core\Di\Container::class,
    \Core\Api\Router\RequestInterface::class => \Core\Router\Request::class,
    \Core\Api\Router\ResponseInterface::class => \Core\Router\Response::class,
    \Core\Api\Di\DiManagerInterface::class => \Core\Di\DiManager::class
];
